"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result1;
result1 = _productService.GetAll();
console.log(result1);
var result2;
result2 = _productService.GetById(2);
console.log(result2);
var result3 = new Product_1.Product();
result3.name = "Monster";
result3.price = 12332;
result3.category = "Bilgisayar";
_productService.SaveProduct(result3);
result1 = [];
result1 = _productService.GetAll();
console.log(result1);
var result4 = new Product_1.Product();
result4.id = 3;
result4.name = "Vestel4404";
result4.price = 20212;
result4.category = "Televizyon";
_productService.SaveProduct(result4);
result1 = [];
result1 = _productService.GetAll();
console.log(result1);
var result5 = new Product_1.Product();
result5.id = 2;
_productService.DeleteProduct(result5);
result1 = [];
result1 = _productService.GetAll();
console.log(result1);
